### ISSUE TITLE
[fix] Test functions

### ISSUE THREAD

**Issue by get6** [42-Jolly-pingpong/back-end#45]
## 🪜 Branch

develop

## 🌐 Domain

- 회원가입
- 로그인
- 메인
- 게임
- 채팅

## 📢 Description

테스트하면서 에러를 고칩니다.

**Comment by SOONG-E** [comment]
여기 브런치에서 오류 고치면 되나여?? 아님 선황님만 쓰시는 건가여?

**Comment by get6** [comment]
저만 쓰려고 햇어요 유정님도 만들어서 진행해주세요~

**Comment by SOONG-E** [comment]
> 저만 쓰려고 햇어요 유정님도 만들어서 진행해주세요~

옙 ㄱ-
